export const loginStyles = {
  page: {
    height: { xs: 'auto', lg: '100vh' },
    overflow: { xs: 'auto', lg: 'hidden' },
    display: 'flex',
    gap: { xs: 4, lg: 6 },
    flexDirection: { xs: 'column', lg: 'row' },
    background: (theme) => theme.palette.background.paper,
    mt: { xs: '8px', lg: 0 },
  },
  storyPanel: {
    width: { xs: '100%', lg: '50%' },
    flex: { xs: 'none', lg: '0 0 50%' },
    height: { xs: 'auto', lg: '100%' },
    maxHeight: { xs: 340, sm: 'none', md: 'none', lg: 'none' },
    borderRadius: { xs: 0, sm: 0, md: '24px', lg: '32px' },
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    pl: { xs: 0, sm: 0, lg: 8 },
    pt: { xs: 0, lg: 0 },
    pb: { xs: 0, lg: 0 },
    marginTop: { xs: 1, lg: 0 },
  },
  storyImageWrap: {
    width: { xs: '100%', sm: '100%', md: '100%', lg: '100%' },
    maxWidth: '100%',
    height: { xs: 320, sm: 400, md: 500, lg: '100%' },
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    margin: '0 auto',
    borderRadius: '32px',
  },
  innerImageBox: {
    width: { xs: '80%', sm: '50%', md: '55%', lg: '90%' },
    maxWidth: 600,
    height: 'auto',
    borderRadius: '24px',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  storyImage: {
    width: '100%',
    height: 'auto',
    maxWidth: '100%',
    objectFit: 'contain',
    objectPosition: 'center',
    margin: 0,
    borderRadius: 'inherit',
    clipPath: 'inset(0 round 32px)',
    WebkitClipPath: 'inset(0 round 32px)',
    display: 'block',
  },
  linkNoDecoration: {
    textDecoration: 'none',
  },
  passwordIconButton: {
    color: 'primary.dark',
    padding: { xs: '8px', sm: '12px' },
    '& svg': {
      width: { xs: '18px', sm: '24px' },
      height: { xs: '18px', sm: '24px' },
    },
  },
  panelEyebrow: {
    fontSize: 14,
    fontWeight: 600,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    color: 'secondary.dark',
  },
  panelTitle: {
    fontWeight: 700,
    color: 'primary.dark',
  },
  panelSubcopy: {
    color: 'primary.main',
    maxWidth: 500,
    lineHeight: 1.6,
  },
  tutorStack: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  infoCard: {
    borderRadius: 3,
    p: 2.5,
    display: 'flex',
    gap: 2,
    alignItems: 'center',
    backgroundColor: 'background.paper',
    boxShadow: (theme) => `0 20px 40px ${theme.palette.secondary.main}40`,
  },
  learnerCard: {
    backgroundColor: 'natural.main',
  },
  avatar: {
    position: 'relative',
    width: 72,
    height: 72,
    borderRadius: 3,
    overflow: 'hidden',
    flexShrink: 0,
  },
  cardTitle: {
    fontWeight: 600,
    color: 'primary.dark',
  },
  cardCaption: {
    mt: 0.5,
    fontSize: 14,
    color: 'primary.main',
  },
  skillBadges: {
    display: 'flex',
    gap: 2,
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  badge: {
    borderRadius: 999,
    px: 2,
    py: 0.75,
    fontWeight: 600,
    fontSize: 14,
  },
  badgePrimary: {
    backgroundColor: (theme) => `${theme.palette.pink.main}33`,
    color: (theme) => theme.palette.error.dark,
  },
  badgeSecondary: {
    backgroundColor: (theme) => `${theme.palette.blue.main}33`,
    color: (theme) => theme.palette.info.dark,
  },
  badgeSignal: {
    borderRadius: 999,
    px: 2,
    py: 0.75,
    backgroundColor: (theme) => `${theme.palette.warning.light}80`,
    display: 'inline-flex',
    gap: 0.5,
  },
  signalBar: {
    width: 6,
    borderRadius: 999,
    backgroundColor: 'secondary.main',
  },
  decorationOne: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: '50%',
    backgroundColor: (theme) => `${theme.palette.background.paper}73`,
    top: -120,
    right: -80,
    display: { xs: 'none', lg: 'block' },
  },
  decorationTwo: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: '50%',
    backgroundColor: (theme) => `${theme.palette.secondary.light}59`,
    bottom: -90,
    left: -60,
    display: { xs: 'none', lg: 'block' },
  },
  formPanel: {
    width: { xs: '100%', lg: '50%' },
    flex: { xs: 'none', lg: '0 0 50%' },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    overflow: { xs: 'visible', lg: 'auto' },
    minWidth: 0,
    py: { xs: 2, sm: 3, lg: 4 },
    px: { xs: 0, sm: 2 },
  },
  formCard: {
    width: '100%',
    maxWidth: 650,
    borderRadius: { xs: 3, md: 4 },
    pr: { xs: 2, sm: 4, lg: '80px' },
    pl: { xs: 2, sm: 4 },
    ml: { lg: 0 },
    my: 'auto',
  },
  cardEyebrow: {
    textAlign: 'center',
    fontSize: { xs: 18, sm: 20, md: 24 },
    fontWeight: 600,
    mb: 2,
  },
  switcherWrapper: {
    display: 'flex',
    justifyContent: 'center',
  },
  switcher: {
    display: 'inline-flex',
    backgroundColor: 'natural.main',
    borderRadius: 999,
    p: 0.5,
    gap: 0.5,
    mx: 'auto',
  },
  switchButton: {
    borderRadius: 999,
    px: 2.5,
    py: 0.75,
    fontWeight: 600,
    color: 'primary.dark',
    textTransform: 'none',
  },
  switchActive: {
    backgroundColor: 'yellow.main',
    color: 'primary.dark',
    boxShadow: (theme) => `0 10px 20px ${theme.palette.yellow.main}73`,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: 1.5,
    mt: 2,
  },
  textField: {
    '& .MuiOutlinedInput-root': {
      borderRadius: 999,
      backgroundColor: 'background.paper',
    },
    '& fieldset': {
      borderColor: 'warning.light',
    },
    '&:hover fieldset': {
      borderColor: 'secondary.main',
    },
    '&.Mui-focused fieldset': {
      borderColor: 'secondary.main',
    },
  },
  fieldContainer: {
    mb: 1.5,
  },
  fieldContainerSmall: {
    mb: 1,
  },
  fieldLabel: {
    mb: 0.5,
    fontSize: { xs: '0.75rem', sm: '1rem' },
    fontWeight: 500,
  },
  textFieldInputProps: {
    borderRadius: '30px',
    border: (theme) => `2px solid ${theme.palette.warning.light}`,
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    px: { xs: 1.5, sm: 2 },
    py: { xs: 0.75, sm: 1 },
    height: { xs: 42, sm: 65 },
    fontSize: { xs: '0.875rem', sm: '1rem' },
  },
  textFieldInputPropsPlaceholder: {
    '::placeholder': { color: 'text.secondary', opacity: 0.6 },
  },
  formMeta: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 3,
  },
  rememberMeLabel: {
    m: 0,
    fontSize: '0.875rem',
    color: 'text.secondary',
    '& .MuiFormControlLabel-label': {
      fontSize: '0.875rem',
      color: 'text.secondary',
    },
  },
  forgotPasswordButton: {
    textTransform: 'none',
    fontWeight: 400,
    color: 'text.secondary',
    fontSize: { xs: '0.75rem', sm: '0.875rem' },
  },
  socialButtonContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
  },
  primaryButton: {
    mt: 2,
    borderRadius: 999,
    py: { xs: 1, sm: 1.25 },
    textTransform: 'none',
    fontSize: { xs: 14, sm: 16 },
    fontWeight: 600,
    backgroundColor: 'yellow.main',
    color: 'primary.dark',
    boxShadow: 'none',
  },
  divider: {
    my: { xs: 2, sm: 3, lg: 4 },
    fontSize: { xs: 10, sm: 12 },
    fontWeight: 600,
    color: 'primary.main',
  },
  socialRow: {
    display: 'flex',
    gap: { xs: 1, sm: 2 },
    flexWrap: 'wrap',
    pb: { xs: 2, sm: 4 },
  },
  socialButton: {
    flex: { xs: '1 1 100%', sm: '1 1 100%', md: '1 1 45%' },
    borderRadius: 999,
    borderColor: 'warning.light',
    textTransform: 'none',
    fontWeight: 600,
    color: 'text.primary',
    py: { xs: 1, sm: 1.25 },
  },
  backButton: {
    position: 'absolute',
    top: { xs: 10, lg: 20 },
    left: { xs: 10, lg: 20 },
    zIndex: 10,
    minWidth: 'auto',
    borderRadius: '50%',
    width: { xs: 36, lg: 40 },
    height: { xs: 36, lg: 40 },
    p: 0,
    backgroundColor: 'background.paper',
    color: 'primary.dark',
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    '&:hover': {
      backgroundColor: 'natural.main',
    },
  },
  roleBadge: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    mt: 2,
    mb: 1,
    px: 2,
    py: 1,
    borderRadius: 2,
    backgroundColor: 'yellow.main',
    color: 'primary.dark',
    fontSize: '0.875rem',
    fontWeight: 600,
  },
};
