export const roleModalStyles = {
  dialogPaper: {
    borderRadius: '16px',
    border: '2px solid',
    borderColor: 'primary.main',
    backgroundColor: 'background.default',
    maxWidth: { xs: '90%', sm: '600px' },
    mx: { xs: 2, sm: 'auto' },
  },
  dialogContent: {
    px: { xs: 2, sm: 4, md: 6 },
    py: { xs: 2, sm: 3, md: 4 },
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: { xs: 2, sm: 3, md: 4 },
  },
  title: {
    fontSize: { xs: '1.25rem', sm: '1.5rem' },
    fontWeight: 600,
    color: 'text.primary',
    textAlign: 'center',
    mb: { xs: 1, sm: 2 },
  },
  cardsContainer: {
    display: 'flex',
    gap: { xs: 1.5, sm: 3 },
    width: '100%',
    justifyContent: 'center',
    flexDirection: { xs: 'column', sm: 'row' },
  },
  card: {
    flex: 1,
    minWidth: { xs: '100%', sm: '150px', md: '200px' },
    backgroundColor: 'background.paper',
    border: '1px solid',
    borderColor: 'divider',
    borderRadius: '12px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 8px 16px rgba(0, 0, 0, 0.1)',
    },
    '&:active': {
      transform: 'translateY(-2px)',
    },
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: { xs: 1, sm: 2 },
    p: { xs: 1.5, sm: 2, md: 3 },
    '&:last-child': {
      paddingBottom: { xs: 1.5, sm: 2, md: 3 },
    },
  },
  iconContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    mb: { xs: 0.5, sm: 1 },
    width: { xs: 60, sm: 80, md: 100 },
    height: { xs: 60, sm: 80, md: 100 },
  },
  icon: {
    objectFit: 'contain',
    width: '100%',
    height: '100%',
  },
  roleButton: {
    backgroundColor: 'primary.main',
    color: 'primary.contrastText',
    fontWeight: 600,
    borderRadius: '8px',
    py: { xs: 1, sm: 1.5 },
    px: { xs: 2, sm: 3 },
    textTransform: 'none',
    fontSize: { xs: '0.875rem', sm: '1rem' },
    boxShadow: 'none',
    display: 'inline-block',
  },
};
