export const uploadProfileStyles = {
  page: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1.1fr 1fr' },
    minHeight: '100vh',
    backgroundColor: 'background.default',
  },
  heroPanel: {
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: 'natural.main',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    px: { xs: 3, md: 6 },
    py: { xs: 6, md: 8 },
  },
  heroImage: {
    width: '100%',
    maxWidth: 520,
    height: 'auto',
    objectFit: 'contain',
  },
  formPanel: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    px: { xs: 2, md: 6 },
    py: { xs: 6, md: 8 },
    backgroundColor: 'background.default',
  },
  formCard: {
    width: '100%',
    maxWidth: 560,
    backgroundColor: 'background.paper',
    borderRadius: 3,
    boxShadow: '0 12px 30px rgba(0,0,0,0.08)',
    p: { xs: 3, md: 4 },
    border: '1px solid',
    borderColor: 'divider',
  },
  title: {
    fontSize: { xs: '1.6rem', md: '1.9rem' },
    fontWeight: 700,
    textAlign: 'center',
    color: 'primary.main',
    mb: 1,
  },
  subtitle: {
    textAlign: 'center',
    color: 'text.secondary',
    maxWidth: 460,
    mx: 'auto',
    mb: 3,
    fontSize: '1rem',
  },
  requirementsBox: {
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' },
    gap: 1.5,
    backgroundColor: 'natural.main',
    borderRadius: 2,
    p: 2,
    border: '1px dashed',
    borderColor: 'warning.light',
    mb: 3,
  },
  requirementItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    color: 'text.primary',
    fontSize: '0.95rem',
  },
  dropzone: {
    border: '2px dashed',
    borderColor: 'warning.light',
    borderRadius: 2,
    p: 3,
    textAlign: 'center',
    backgroundColor: 'background.paper',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    '&:hover': {
      borderColor: 'secondary.main',
      backgroundColor: 'natural.main',
    },
  },
  previewImage: {
    maxWidth: '100%',
    maxHeight: 360,
    borderRadius: 2,
    objectFit: 'contain',
    border: '1px solid',
    borderColor: 'divider',
    display: 'block',
    margin: '0 auto',
  },
  buttonPrimary: {
    mt: 2,
    borderRadius: 2,
    textTransform: 'none',
    py: 1.2,
    fontWeight: 600,
  },
  secondaryLink: {
    mt: 1,
    textTransform: 'none',
    color: 'primary.main',
    '&:hover': { textDecoration: 'underline' },
  },
  successBox: {
    textAlign: 'center',
    py: 4,
  },
};
