export const TeacherHomepageStyles = {
  mainContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'background.default',
  },
  contentWrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '24px 24px',
    flex: 1,
    width: '100%',
  },
  welcomeHeader: {
    marginBottom: '32px',
    backgroundColor: 'background.paper',
    borderRadius: '25px',
    padding: { xs: '20px', md: '32px' },
    width: '100%',
  },
  welcomeTitle: {
    fontSize: { xs: '1.5rem', sm: '1.7rem', md: '2rem' },
    fontWeight: 500,
    color: 'primary.dark',
    marginBottom: '8px',
    marginLeft: { xs: '0px', sm: '10px' },
  },
  welcomeSub: {
    color: 'darkGrey.light',
    marginBottom: '24px',
    marginLeft: { xs: '0px', sm: '10px' },
    fontSize: { xs: '1rem', sm: '1.1rem', md: '1.2rem' },
  },
  statBadge: (variant) => ({
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1.5,
    padding: { xs: '6px 16px', md: '8px 20px' },
    borderRadius: '25px',
    backgroundColor: variant === 'yellow' ? 'natural.main' : 'success.pastel',
    border: `1px solid ${variant === 'yellow' ? 'warning.main' : 'success.main'}`,
    color: variant === 'yellow' ? 'warning.dark' : 'success.dark',
    fontWeight: 500,
    marginLeft: { xs: '0px', sm: '10px' },
  }),
  filterSection: {
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    gap: 2,
    marginBottom: '32px',
    alignItems: { xs: 'stretch', lg: 'center' },
  },
  searchInput: {
    flex: { xs: 'none', lg: 1 },
    maxWidth: '1200px',
    backgroundColor: 'background.paper',
    '& .MuiOutlinedInput-root': {
      borderRadius: '12px',
      '& fieldset': { borderColor: 'background.paper' },
    },
    borderRadius: '12px',
  },
  selectFilter: {
    flex: {
      xs: 'calc(50% - 8px)',
      sm: 'calc(20% - 12px)',
      lg: 'none',
    },
    minWidth: { xs: '100%', sm: '150px', lg: '150px' },
    backgroundColor: 'background.paper',
    borderRadius: '12px',
    '& .MuiOutlinedInput-notchedOutline': { borderColor: 'background.paper' },
  },
  createBtn: {
    backgroundColor: 'yellow.main',
    color: 'primary.dark',
    fontWeight: 700,
    borderRadius: '12px',
    padding: '10px 24px',
    textTransform: 'none',
    '&:hover': { backgroundColor: 'warning.main' },
    minWidth: { xs: '100%', sm: '140px' },
  },
  testGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: '1fr 1fr',
      lg: '1fr 1fr 1fr',
    },
    gap: '24px',
    marginBottom: '48px',
    minHeight: '400px',
    alignContent: 'start',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 1,
    paddingBottom: '40px',
  },
};
