export const TeacherHomepageStyles = {
  mainContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: 'background.default',
  },
  contentWrapper: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '24px 24px',
    flex: 1,
    width: '100%',
  },
  welcomeHeader: {
    marginBottom: '32px',
    backgroundColor: '#fff',
    borderRadius: '24px',
    padding: '24px',
    width: '100%',
  },
  welcomeTitle: {
    fontSize: { xs: '1.5rem', md: '3rem' },
    fontWeight: 600,
    color: 'primary.main',
  },
  welcomeSub: {
    color: 'text.secondary',
    fontSize: { xs: '0.9rem', md: '1rem' },
  },

  filterSection: {
    mt: 4,
    display: 'flex',
    flexDirection: { xs: 'column', lg: 'row' },
    gap: 2,
    marginBottom: '32px',
    alignItems: { xs: 'stretch', lg: 'center' },
  },
  searchInput: {
    flex: { xs: 'none', lg: 1 },
    maxWidth: '1200px',
    backgroundColor: 'background.paper',
    borderRadius: '25px',
    border: '1px solid',
    borderColor: 'divider',
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
  },
  selectFilter: {
    flex: {
      xs: 'calc(50% - 8px)',
      sm: 'calc(20% - 12px)',
      lg: 'none',
    },
    minWidth: { xs: '100%', sm: '150px', lg: '150px' },
    backgroundColor: 'background.paper',
    borderRadius: '25px',
    border: '1px solid',
    borderColor: 'divider',
    '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
    '& .MuiSelect-select': {
      display: 'flex',
      alignItems: 'center',
      gap: 1,
    },
  },
  createBtn: {
    backgroundColor: 'yellow.main',
    color: 'primary.dark',
    fontWeight: 700,
    borderRadius: '12px',
    padding: '10px 24px',
    textTransform: 'none',
    boxShadow: 'none',
    '&:hover': {
      backgroundColor: 'warning.main',
      boxShadow: 'none',
    },
    minWidth: { xs: '100%', sm: '140px' },
  },
  testGrid: {
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      md: '1fr 1fr',
      lg: '1fr 1fr 1fr',
    },
    gap: '24px',
    marginBottom: '48px',
    minHeight: '400px',
    alignContent: 'start',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 1,
    paddingBottom: '40px',
  },
};
