'use client';

import { keyframes } from '@mui/material';

const shimmer = keyframes`
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
`;

const skeletonBase = {
  background: 'linear-gradient(90deg, #f0f0f0 25%, #e0e0e0 50%, #f0f0f0 75%)',
  backgroundSize: '200% 100%',
  animation: `${shimmer} 1.5s infinite linear`,
};

export const listeningtestStyles = {
  mainContainer: {
    // pb: { xs: 1, md: 2 },
    backgroundColor: 'background.paper',
  },
  // -------- Test Heading Section ---------
  testHeadingContainer: {
    height: 'auto',
    width: '100%',
    backgroundColor: '#fff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 1,
    px: { xs: 0, md: 3 },
    py: { xs: 1, md: 2 },
  },
  separatorLine: {
    height: '2px',
    width: '100vw',
    position: 'relative',
    backgroundColor: 'orange.light',
    left: '50%',
    transform: 'translateX(-50%)',
    border: 'none',
  },
  backButton: {
    width: { xs: 'auto', md: '200px' },
    color: 'gray.main',
    fontSize: '1rem',
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    transform: 'translateX(-10px)',
  },
  summitButtonWrapper: {
    width: { xs: 'auto', sm: '200px' },
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  submitButton: {
    backgroundColor: 'yellow.main',
    color: 'primary.main',
    fontSize: { xs: '0.7rem', md: '1rem' },
    fontWeight: 500,
    textTransform: 'none',
    whiteSpace: 'nowrap',
    '&:hover': {
      backgroundColor: 'warning.dark',
      boxShadow: 'none',
    },
    px: 2.5,
  },
  nameTestAndFormatPart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
  },
  nameTest: {
    fontSize: { xs: '0.9rem', md: '1.3rem' },
    fontWeight: 600,
    color: 'primary.main',
    width: '100%',
    textAlign: 'center',
    maxWidth: '400px',
  },
  nameTestSkeleton: {
    ...skeletonBase,
    width: '300px',
    height: '24px',
    borderRadius: '0.5rem',
    display: 'inline-block',
  },
  formatName: {
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 500,
    color: 'red.text',
    textAlign: 'center',
  },
  formatNameSkeleton: {
    ...skeletonBase,
    fontSize: { xs: '0.8rem', md: '1rem' },
    width: '180px',
    height: '1.2em',
    borderRadius: '0.5rem',
    display: 'block',
    marginTop: '4px',
  },
  // -------- List Part Section ---------
  listPartContainer: {
    position: 'relative',
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    userSelect: 'none',
    gap: { xs: 1, md: 2 },
    py: 1,
  },
  boxPart: {
    width: '80px',
    height: '36px',
    borderRadius: '0.5rem',
    backgroundColor: 'gray.100',
    border: '2px solid',
    borderColor: 'gray.main',
    color: 'text.gray',
    fontSize: '1rem',
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    '&:hover': {
      borderColor: 'orange.light',
    },
  },
  boxPartSkeleton: {
    ...skeletonBase,
    width: '80px',
    height: '36px',
    borderRadius: '0.5rem',
    border: '2px solid',
    borderColor: 'gray.main',
  },
  timeLeft: {
    userSelect: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    color: 'text.primary',
    px: 0,
    py: 0.5,
    fontWeight: 600,
    fontSize: { xs: '0.8rem', md: '1.2rem' },
    minWidth: { xs: '0', sm: '200px' },
  },
  timeLeftSkeleton: {
    ...skeletonBase,
    width: '80px',
    height: '24px',
    borderRadius: '0.5rem',
    display: 'inline-block',
  },
  // -------- Part Content Section ---------
  spinnerWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '200px',
    height: '200px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    zIndex: 10,
  },
  // -------- Stepper Section ---------
  stepperContainer: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    userSelect: 'none',
    pt: 6,
    pb: 2,
  },
  nextButton: {
    width: '100px',
    backgroundColor: 'dark.main',
    color: 'background.paper',
    fontSize: { xs: '0.9rem', md: '1rem' },
    fontWeight: 500,
    textTransform: 'none',
    '&:hover': {
      backgroundColor: 'darkGrey.light',
      boxShadow: 'none',
    },
    px: 2.5,
    py: 0.5,
  },
};

export const listeningPartStyles = {
  container46: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: '4fr 6fr',
    },
    justifyContent: 'center',
    alignItems: 'start',
    gap: 2,
    p: 2,
  },
  containerColRow: {
    width: '100%',
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    height: '100%',
    maxHeight: '100%',
    overflow: 'hidden',
    alignItems: 'stretch',
    gap: 0,
    p: 2,
  },
  container55: {
    width: '100%',
    display: 'grid',
    gridTemplateColumns: {
      xs: '1fr',
      sm: '5fr 5fr',
    },
    justifyContent: 'center',
    alignItems: 'start',
    gap: 2,
    p: 2,
  },
  containerCol: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    p: 2,
  },
  basicFlexColCenStart: {
    userSelect: 'none',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 2,
  },
  // -------- Audio Section ---------
  // -------- Instruction Section ---------
  instructionContainer: {
    userSelect: 'none',
    width: '100%',
    height: 'auto',
    display: 'grid',
    gridTemplateColumns: 'auto 1fr',
    alignItems: 'start',
    gap: 2,
    backgroundColor: 'background.paper',
    borderRadius: '0.5rem',
    border: '2px solid',
    borderColor: 'orange.light',
    p: 2,
  },
  instructionWrapper: {
    width: '100%',
    height: 'auto',
    backgroundColor: 'background.paper',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  // -------- Question Section ---------
  questionSection: {
    position: 'relative',
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    backgroundColor: 'background.paper',
    borderRadius: '0.5rem',
    border: '1px solid',
    borderColor: 'gray.main',
    gap: 3,
    p: 3,
  },
  listQuestionContainerGrid: {
    width: '100%',
    height: 'auto',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' },
    alignItems: 'start',
    gap: 1,
  },
  innerDecorQuestionSection: {
    position: 'absolute',
    width: 'calc(100% - 3 * 16px)',
    height: '16px',
    top: '-8px',
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'background.default',
    zIndex: 10,
    borderRadius: '1rem',
    clipPath: 'inset(8px 0px 0px 0px)',
  },
  innerInstruction: {
    width: '100%',
    height: 'auto',
    backgroundColor: 'background.default',
    borderRadius: '0.5rem',
    border: '1px solid',
    borderColor: 'orange.light',
    color: 'primary.main',
    fontSize: { xs: '0.8rem', md: '0.9rem' },
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 1,
    cursor: 'pointer',
    px: 2,
    py: 1,
  },
  questionContainerCol: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 1,
  },
  questionContainerRow: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    borderRadius: '0.5rem',
    border: '2px solid',
    borderColor: 'gray.main',
    gap: 1,
    py: 1,
    px: 2,
  },
  questionTextContainer: {
    width: '100%',
    height: 'auto',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 1,
  },
  questionLabelRectangle: {
    userSelect: 'none',
    flexShrink: 0,
    width: '24px',
    height: '32px',
    color: 'background.paper',
    backgroundColor: 'dark.main',
    borderRadius: '0.5rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 500,
  },
  questionLabelCircle: {
    userSelect: 'none',
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    backgroundColor: 'dark.main',
    color: 'background.paper',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 500,
  },
  questionText: {
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 400,
    color: 'dark.main',
    wordBreak: 'break-word',
    overflowWrap: 'anywhere',
  },
  // -------- Option Section ---------
  optionsGrid: {
    width: '100%',
    height: 'auto',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', md: '1fr 1fr 1fr' },
    gap: 2,
  },
  optionsGridRow: {
    width: '100%',
    height: 'auto',
    display: 'grid',
    gridTemplateRow: { xs: '1fr', md: '1fr 1fr 1fr' },
    gap: 1,
  },
  optionContainer: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 1,
    overflow: 'hidden',
  },
  imgContainer: {
    userSelect: 'none',
    width: '100%',
    height: '150px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'background.gray',
    borderRadius: '0.5rem',
    overflow: 'hidden',
    '& img': {
      width: '100%',
      height: 'auto',
      objectFit: 'cover',
    },
  },
  labelButton: {
    width: '100%',
    backgroundColor: 'yellow.main',
    color: 'primary.main',
    fontSize: { xs: '0.7rem', md: '1rem' },
    fontWeight: 500,
    textTransform: 'none',
    '&:hover': {
      backgroundColor: 'warning.dark',
      boxShadow: 'none',
    },
    px: 2.5,
  },
  // -------- Passage Section ---------
  passageContainer: {
    width: '100%',
    height: 'auto',
    backgroundColor: 'background.paper',
    borderRadius: '0.5rem',
    border: '1px solid',
    borderColor: 'gray.main',
    p: { xs: 1, sm: 2, md: 3 },
  },
  // -------- Input Section ---------
  inputQuestion: {
    width: '100%',
    '& .MuiInput-root': {
      fontSize: '1rem',
      '&:before': { borderBottomColor: 'black' },
      '&:after': { borderBottomColor: 'black' },
    },
    '& input': {
      fontSize: { xs: '0.7rem', md: '0.9rem' },
      padding: '4px 0',
    },
  },
  // -------- Other Section ---------
  audioAndOptionsContainer: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    gap: 3,
    px: 4,
  },
  matchingQuestionAnswerContainerGrid: {
    width: '100%',
    height: 'auto',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', sm: '6fr 4fr' },
    alignItems: 'start',
    gap: 1,
  },
};
