export const listeningtestStyles = {
  mainContainer: {
    // pb: { xs: 1, md: 2 },
    backgroundColor: 'background.paper',
  },
  // -------- Test Heading Section ---------
  testHeadingContainer: {
    height: 'auto',
    width: '100%',
    backgroundColor: '#fff',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    userSelect: 'none',
    gap: 1,
    px: 3,
    py: 2,
  },
  separatorLine: {
    height: '2px',
    width: '100vw',
    position: 'relative',
    backgroundColor: 'orange.light',
    left: '50%',
    transform: 'translateX(-50%)',
    border: 'none',
  },
  backButton: {
    color: 'gray.main',
    fontSize: { xs: '0.7rem', md: '1rem' },
    fontWeight: 500,
    cursor: 'pointer',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    transform: 'translateX(-10px)',
  },
  submitButton: {
    backgroundColor: 'yellow.main',
    color: 'primary.main',
    fontSize: { xs: '0.7rem', md: '1rem' },
    fontWeight: 500,
    textTransform: 'none',
    '&:hover': {
      backgroundColor: 'warning.dark',
      boxShadow: 'none',
    },
    px: 2.5,
  },
  nameTestAndFormatPart: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0,
  },
  nameTest: {
    fontSize: { xs: '1rem', md: '1.3rem' },
    fontWeight: 600,
    color: 'primary.main',
    width: '100%',
    textAlign: 'center',
    maxWidth: '400px',
  },
  formatName: {
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 500,
    color: 'red.text',
  },
  // -------- List Part Section ---------
  listPartContainer: {
    width: '100%',
    height: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    userSelect: 'none',
    gap: 3,
    py: 1,
  },
  boxPart: {
    width: '80px',
    height: '36px',
    borderRadius: '0.5rem',
    backgroundColor: 'gray.100',
    border: '2px solid',
    borderColor: 'gray.main',
    color: 'text.gray',
    fontSize: { xs: '0.8rem', md: '1rem' },
    fontWeight: 500,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    '&:hover': {
      borderColor: 'orange.light',
    },
  },
};
